- name: VC UPDATE
        run: |
          mkdir -p assets
          
          BASE_URL="https://vi-ra-caisse-561480809159.europe-west2.run.app"
          
          curl -H "User-Agent: Mozilla/5.0" -L -o index.html "$BASE_URL/"
          curl -H "User-Agent: Mozilla/5.0" -L -o assets/index-CUzW0L13.js "$BASE_URL/assets/index-CUzW0L13.js"
          curl -H "User-Agent: Mozilla/5.0" -L -o _websocket-interceptor.js "$BASE_URL/_websocket-interceptor.js?v=1"
          
          curl -H "User-Agent: Mozilla/5.0" -L -o _service-worker.js "$BASE_URL/_service-worker.js" || echo "Service worker not found, skipping."
